"use client"

import type React from "react"

import { createContext, useState, useContext, useEffect } from "react"

type Language = {
  code: string
  name: string
}

type LanguageContextType = {
  currentLanguage: string
  setLanguage: (code: string) => void
  languages: Language[]
  t: (key: string) => string
}

const languages: Language[] = [
  { code: "uz", name: "Uzbek" },
  { code: "ru", name: "Russian" },
  { code: "en", name: "English" },
]

// Simple translations for demonstration
const translations: Record<string, Record<string, string>> = {
  uz: {
    "nav.home": "Asosiy sahifa",
    "nav.about": "Biz haqimizda",
    "nav.services": "Xizmatlarimiz",
    "nav.portfolio": "Loyihalarimiz",
    "nav.process": "Ish jarayon",
    "nav.contact": "Biz bilan bog'lanish",
    "hero.title": "Biz biznesingizni rivojlantiruvchi texnologiyalarni yaratamiz!",
    "hero.subtitle":
      "TrueLiTech – bu biznes uchun to‘liq raqamli va har qanday murakkablikdagi yechimlarni taqdim etuvchi IT-kompaniya: IT-konsalting, veb-loyihalar, mobil ilovalar, veb-saytlar va platformalarni ishlab chiqish hamda qo‘llab-quvvatlash o'z ichiga oladi.",
    "hero.cta.start": "Konsultatsiya yozilish",
    "hero.cta.work": "Loyihlarimizni ko'rish",
    "services.title": "Yo'nalishlarimiz",
    "services.subtitle": "Biznesingizni raqamlashtirish orqali qanday imkoniyatlar ochilishini bilasizmi? Biz sizga biznesingizning haqiqiy potensialini ochib berish uchun yordam beramiz. Quyida biz ishlaydigan asosiy yo‘nalishlar keltirilgan.",
    "services.e_commerce_title": "Elektron do'konlar uchun yechimlar",
    "services.e_commerce_description": "Biz onlayn do‘konlar uchun mijozlarni jalb qilish, xodimlarni boshqarish va turli xil tahlillarni amalga oshirish imkonini beruvchi veb-saytlar va mobil ilovalarni ishlab chiqamiz.",
    "services.healthcare_title": "Sog'liqni saqlash",
    "services.healthcare_description": "Biz klinikalar va tibbiyot muassasalari uchun bemorlarni jalb qilish, xodimlarni boshqarish va turli xil tibbiy tahlillarni amalga oshirish imkonini beruvchi veb-saytlar va mobil ilovalarni ishlab chiqamiz.",
    "services.finance_and_fintech_title": "Moliya va Fintech",
    "services.finance_and_fintech_description": "Moliya va fintech biznesingizni rivojlantirishga to‘sqinlik qilayotgan muammolardan xalos bo‘ling! Biz mijozlarni jalb qilish, tranzaktsiyalarni soddalashtirish va marketing strategiyangizni kuchaytiruvchi raqamli echimlarni yaratamiz.",
    "services.education_title": "Ta'lim yo'nalishi",
    "services.education_description": "Ta’lim biznesingizni rivojlantiring! Biz talabalarni jalb qilish, o‘quv jarayonini avtomatlashtirish va marketingni kuchaytirish uchun mobil ilovalar, CRM va ERP tizimlarini yaratamiz.",
    "services.real_estate_title": "Ko'chmas mulk",
    "services.real_estate_description": "Ko‘chmas mulk savdosidagi murakkab jarayonlarni soddalashtiring! Biz mijozlarni jalb qilish, mulkni boshqarish va marketingni kuchaytirish uchun mobil ilovalar, CRM va ERP tizimlarini yaratamiz.",
    "services.tourism_title": "Turizm",
    "services.tourism_description": "Sayohat ixlosmandlari internetda turpaketlarni izlayotganini bilasizmi? Ammo sizning veb-saytingiz yoki mobil ilovangiz yo‘qmi? Biz sizga mijozlarni jalb qilish, buyurtmalarni boshqarish va marketingni kuchaytiruvchi raqamli echimlarni yaratamiz!",
    "services.start_ups_title": "SaaS va Startuplar",
    "services.start_ups_description": "Startapingiz tezkor MVP-ga muhtoj, lekin vaqt va resurslar yetishmayaptimi? Biz samarali MVP yaratib, bozorda raqobatbardosh bo‘lishingiz va auditoriyangizni tezroq egallashingizga yordam beramiz.",
    "services.food_beverage_title": "Umumiy ovqatlanish",
    "services.food_beverage_description": "Mijozlaringiz raqobatchilaringizdan onlayn buyurtma berayotganini bilasizmi? Ammo sizning veb-saytingiz yoki mobil ilovangiz yo‘qmi? Biz restoran va yetkazib berish xizmatlari uchun mijozlarni jalb qiluvchi, buyurtmalarni avtomatlashtiruvchi va sodiqlikni oshiruvchi raqamli echimlarni yaratamiz!",
    "services.fitness_title": "Fitnes va Salomatlik",
    "services.fitness_description": "Mijozlaringiz onlayn sport va sog‘liqni saqlash xizmatlarini izlayotganini bilasizmi? Ammo sizning veb-saytingiz yoki mobil ilovangiz yo‘qmi? Biz fitnes-klublar va sog‘lom turmush tarzini targ‘ib qiluvchi bizneslar uchun mijozlarni jalb qiluvchi, xizmatlarni avtomatlashtiruvchi va sodiqlikni oshiruvchi raqamli echimlarni yaratamiz!",
    "services.learn_more": "Batafsil ma'lumot",
    "services.our_process_title": "Bizning ish jarayonimiz",
    "services.our_process_description": "Biz biznesingiz ehtiyojlariga mos keladigan yuqori sifatli yechimlarni yetkazib berish uchun tuzilgan yondashuvga amal qilamiz.",
    "services.process_discovery_title": "Tadqiqot va analiz",
    "services.process_discovery_description": "Jamoamiz sizning sohangingiz, raqobatchilaringiz va maqsadli auditoriyangizni o‘rganib, strategiyani shakllantiradi.",
    "services.process_research_title": "Dizayn va rejalashtirish",
    "services.process_research_description": "Biz sizning maxsus ehtiyojlaringizga mos keladigan batafsil dizayn va texnik xususiyatlarni yaratamiz.",
"services.process_design_title": "Dizayn va rejalashtirish",
"services.process_design_description": "Biz sizning ehtiyojlaringizga mos keluvchi batafsil dizayn va texnik xususiyatlarni ishlab chiqamiz.",
    "services.process_developement_title": "Dasturlash",
    "services.process_developement_description": "Dasturchilarimiz yechimingizni eng so‘nggi texnologiyalar va eng yaxshi amaliyotlar asosida yaratadilar.",
    "services.process_testing_title": "Test va sifat nazorati",
    "services.process_testing_description": "Jiddiy sinovlar yechimingizning ishonchliligi, xavfsizligi va optimal ishlashini ta’minlaydi.",
    "services.process_launch_title": "Ishga tushirish va qo‘llab-quvvatlash",
    "services.process_launch_description": "Biz yechimingizni ishga tushiramiz va muvaffaqiyatli ishlashini ta’minlash uchun doimiy qo‘llab-quvvatlash va texnik xizmat ko‘rsatamiz.",
    "portfolio.title": "Bizning loyihalarimiz",
    "portfolio.description": "Turli sohalardagi muvaffaqiyatli loyihalarimizni ko‘rib chiqing va biz bizneslarga maqsadlariga erishishda qanday yordam berganimizni bilib oling.",
    "portfolio.all_projects": "Barcha loyihalar",
    "portfolio.e_commerce": "Elektron tijorat",
    "portfolio.healthcare": "Sog‘liqni saqlash",
    "portfolio.finance": "Moliya",
    "portfolio.education": "Ta'lim",
    "portfolio.real_estate": "Ko‘chmas mulk",
    "portfolio.startup": "Startuplar",
    "portfolio.magic": "Magic – zamonaviy veb-ilovalar uchun mo‘ljallangan ilg‘or autentifikatsiya va identifikatsiyani boshqarish yechimi.",
    "portfolio.mayo": "Mayo Clinic – zamonaviy tibbiyot muassasasi bo‘lib, ilg‘or raqamli yechimlardan foydalanib, bemorlarni boshqarish va operatsion samaradorlikni oshiradi.",
    "portfolio.luxboutique": "LuxBoutique onlayn doʻkoni – hashamatli moda brendlari uchun moʻljallangan yuqori sifatli e-commerce sahifasi, nafis dizayn va qulay foydalanuvchi interfeysi bilan.",
    "portfolio.shopease": "ShopEase online platformasi - zamonaviy, koʻp funksiyali onlayn bozor ilgʻor mahsulot boshqaruvi, qulay toʻlov tizimi va kengaytiriladigan infratuzilmaga ega.",
    "portfolio.skillmaster": "SkillMaster Academy - shaxsiy kurslar, sun'iy intellekt asosidagi tavsiyalar va real vaqtda o‘quvchilarning rivojlanishini kuzatish imkoniyatini taqdim etuvchi zamonaviy onlayn ta’lim platformasi.",
    "portfolio.globaltechacademy": "Biz Global Academy uchun kuchli ERP tizimi, qulay mobil ilova va dinamik veb-sayt ishlab chiqdik. Ushbu yechimlar talabalarning boshqaruvini soddalashtirdi, ma’muriy jarayonlarni avtomatlashtirdi va onlayn ta’limga kirishni osonlashtirdi. Bizning yechimlarimiz operatsion samaradorlik va talabalar faolligini oshirib, ta’lim jarayonini yanada soddalashtirdi va interaktiv qildi.",
    "portfolio.hugson": "Biz International Hugson University Online uchun zamonaviy ERP tizimi, qulay mobil ilova va funksional veb-sayt ishlab chiqdik. Ushbu yechimlar ta’lim jarayonini raqamlashtirib, talabalar, o‘qituvchilar va universitet boshqaruvi uchun qulay interfeys yaratdi. Kurslarni boshqarish, reyting va baholash tizimi avtomatlashtirilib, onlayn ta’lim jarayoni ancha samarali va interaktiv bo‘ldi.",
    "portfolio.stargate": "Biz Stargate Medical Center uchun ilg‘or ERP tizimi, qulay mobil ilova va professional veb-sayt ishlab chiqdik. Bizning yechimlarimiz bemorlarni boshqarishni soddalashtirib, qabulni avtomatlashtirish va tibbiy yozuvlarni tezkor olish imkoniyatini yaratadi. Intuitiv boshqaruv paneli shifokorlarga davolash jarayoni, hisob-kitob va diagnostikani samarali kuzatish imkonini beradi, bemorlar esa onlayn qabulga yozilish va telemeditsina xizmatlaridan foydalanish imkoniyatiga ega bo‘ladilar. Ushbu raqamli transformatsiya operatsion samaradorlikni oshirib, yuqori darajadagi tibbiy xizmat ko‘rsatishni ta’minlaydi",
    "portfolio.mondak": "Mobil hamyonlar, bank integratsiyalari va QR to‘lovlar bilan Mondak to‘lov jarayonlarini soddalashtiradi. U xavfsiz, tezkor va samarali bo‘lib, jismoniy shaxslar va bizneslar uchun pul o‘tkazmalari, to‘lovlar va do‘konlardagi xaridlarni naqd pulsiz amalga oshirish imkonini beradi",
    "portfolio.real_property_agency": "Biz ko‘chmas mulk agentliklari, developer kompaniyalar va mustaqil sotuvchilar uchun zamonaviy veb-saytlar, mobil ilovalar va CRM tizimlarini yaratamiz. Platformamiz yordamida mijozlar osonlik bilan e’lon joylashtirishi, mulklarni ko‘rib chiqishi va shartnomalar tuzishi mumkin. Onlayn to‘lovlar, avtomatlashtirilgan bron qilish tizimi va xavfsiz ma’lumot almashinuvi biznesingizni keyingi bosqichga olib chiqadi!",
    "contact.get_intouch": "Biz bilan bog'lanish",
    "contact.description": "Loyihangiz bormi? Biz sizning biznes maqsadlaringizga qanday yordam bera olishimiz haqida suhbatlashaylik.",
    "contact.send_us_message": "Bizga xabar yuboring!",
    "contact.send_description": "Quyidagi formani to'ldiring, biz siz bilan imkon qadar tezroq bog'lanamiz!",
    "contact.contact_info": "Aloqaga chiqish uchun",
    "contact.contact_info_description": "Quyidagi ma'lumotlar orqali biz bilan bevosita bog'laning.",
    "contact.telephone": "Telefon",
    "contact.telegram": "Telegram",
    "contact.address": "Manzil",
    "contact_form.thank_you": "Ishonch bildirganingiz uchun rahmat!",
    "contact_form.success_message": "Xabaringiz muvaffaqiyatli yuborildi. Siz bilan imkon qadar tezroq bog'lanamiz!",
    "contact_form.name": "Ism",
    "contact_form.enter_name": "Ismingizni kiriting...",
    "contact_form.phone": "Telefon raqam",
    "contact_form.enter_phone": "Telefon raqamingizni kiriting...",
    "contact_form.message": "Habar",
    "contact_form.tell_us_more": "Loyihangiz va talablaringiz haqida bizga ayting...",
    "contact_form.send": "Yuborish",
    "contact_form.sending": "Yuborilmoqda",
    "contact_form.name_alert": "Iltimos ismingizni to'liq kiriting!",
    "contact_form.phone_alert": "Iltimos raqamingizni to'liq kiriting!",
    "contact_form.sent": "Yuborildi!",
    "contact_form.sent_description": "Siz bilan tez orada bog'lanamiz!",
    "cta.title": "Biznesingizni o'zgartirishga tayyormisiz?",
    "cta.description": "Keling, sizning biznes maqsadlaringizga erishishingiz va o‘sishingizga qanday yordam bera olishimiz haqida gaplashamiz.",
    "footer.description": "Innovatsion IT yechimlari turli sohalardagi bizneslar uchun. Biz g‘oyalarni kuchli raqamli tajribaga aylantiramiz",
    "footer.quick_links": "Sahifalar",
    "footer.all_rights_reserved": "Barcha huquqlar himoyalangan",
    "services_page.title": "Bizning xizmatlarimiz",
    "services_page.description": "Sizning sohangiz ehtiyojlariga moslashtirilgan kompleks IT yechimlari. Biz texnik tajribani soha bo‘yicha bilim bilan birlashtirib, biznes o‘sishini ta’minlaydigan yechimlarni taqdim etamiz.",
    "services_page.discuss": "Loyihangizni muhokama qilish",
    "services_page.core_service": "Asosiy xizmatlarimiz",
    "services_page.core_service_description": "Texnologiya xizmatlarimizning keng qamrovli to‘plami.",
    "services_page.web_development_title": "Veb-site/dastur ishlab chiqish",
    "services_page.web_development_description": "Tijoriy va korporativ veb-saytlar, web-ilovalar",
    "services_page.web_development_responsive": "Mobil moslashuvchan dizayn",
    "services_page.web_development_powerful": "Kuchli va xavfsiz e-tijorat platformalari",
    "services_page.web_development_content": "Kontent boshqaruv tizimlari (CMS)",
    "services_page.web_development_progressive": "Progressive web-ilovalar (PWA)",
    "services_page.web_development_api": "API ishlab chiqish",
    "services_page.web_development_custom": "Shaxsiylashtirilgan veb-portal yechimlari",
    "services_page.mobile_title": "Mobil ilovalarni ishlab chiqish",
    "services_page.mobile_description": "iOS va Android uchun innovatsion mobil ilovalar",
    "services_page.mobile_ios": "iOS ilova ishlab chiqish",
    "services_page.mobile_android": "Android ilova ishlab chiqish",
    "services_page.mobile_cross": "Kross-platforma yechimlari",
    "services_page.mobile_ui": "Mobile UI/UX design",
    "services_page.mobile_support": "Ilova qo‘llab-quvvatlash va yangilash",
    "services_page.mobile_store": "App Store va Google Play optimizatsiyasi",
    "services_page.ui_title": "UI/UX Dizayn",
    "services_page.ui_description": "Foydalanuvchi ehtiyojlariga mos keluvchi zamonaviy dizayn",
    "services_page.ui_research": "Foydalanuvchi tadqiqotlari",
    "services_page.ui_prototyping": "Wireframe va prototiplash",
    "services_page.ui_visual": "Innovatsion vizual dizayn",
    "services_page.ui_interaction": "Interaktiv dizayn",
    "services_page.ui_testing": "Qulaylikni test qilish (Usability testing)",
    "services_page.ui_designs": "Dizayn tizimlarini yaratish",
    "services_page.mvp_title": "Startaplar uchun MVP",
    "services_page.mvp_description": "Startaplar uchun tezkor MVP ishlab chiqish va bozorga chiqish",
    "services_page.mvp_reality": "Biznes g‘oyani real mahsulotga aylantirish",
    "services_page.mvp_quick": "Tezkor va minimal MVP ishlab chiqish",
    "services_page.mvp_ready": "Investorlarga taqdimot uchun tayyor yechimlar",
    "services_page.erp_title": "ERP/CRM tizimlarini ishlab chiqish",
    "services_page.erp_description": "Biznes jarayonlarini avtomatlashtirish va samaradorlikni oshirish",
    "services_page.erp_finance": "Buxgalteriya va moliyaviy boshqaruv tizimlari",
    "services_page.erp_customer": "Mijozlar bilan ishlash tizimlari (CRM)",
    "services_page.bots_title": "Telegram botlari",
    "services_page.bots_description": "Savdo va xizmat ko‘rsatishni avtomatlashtiruvchi Telegram botlari",
    "services_page.bots_business": "Biznes uchun Telegram bot ishlab chiqish",
    "services_page.bots_orders": "Online buyurtmalar qabul qilish va avtomatlashtirish",
    "services_page.free_consultation": "Bugun biz bilan bog‘laning, loyihangiz talablari haqida muhokama qiling va bepul maslahat oling.",
    "about_page.title": "TrueLiTech haqida",
    "about_page.description": "Biz bizneslarni innovatsion raqamli yechimlar orqali o‘zgartirishga bag‘ishlangan ishtiyoqli va tajribali texnologlar jamoasimiz.",
    "about_page.our_story_title": "Bizning hikoyamiz",
    "about_page.our_story_description": "Kichik qadamlardan soha yetakchiligigacham",
    "about_page.founded_with_vision": "Aniq maqsad bilan tashkil etilgan",
    "about_page.content": "TrueLiTech 2019 yilda aniq bir maqsad bilan tashkil etilgan: bizneslarga texnologiyadan foydalanib o‘z maqsadlariga erishishda yordam berish. Uch nafar ishtiyoqli dasturchidan iborat kichik jamoa sifatida boshlangan ishimiz bugungi kunda 50 dan ortiq mutaxassis ishlaydigan to‘liq xizmat ko‘rsatadigan IT agentligiga aylandi. O‘tgan yillar davomida biz yuzlab mijozlarga ularning o‘ziga xos ehtiyojlariga moslashtirilgan maxsus dasturiy ta’minot yechimlari, veb-ilovalar va raqamli strategiyalar orqali bizneslarini rivojlantirishda yordam berdik. Bugungi kunda biz innovatsiyalarni rivojlantirish va imkoniyatlar chegaralarini kengaytirishda davom etamiz hamda har doim mijozlarimizning muvaffaqiyatini ishimizning markazida tutamiz.",
    "about_page.values": "Qadriyatlarimiz",
    "about_page.values_description": "Ishimiz va mijozlar bilan munosabatlarimizni belgilovchi tamoyillar.",
    "about_page.value_innovation_title": "Innovatsiya",
    "about_page.value_innovation_description": "Biz ilg‘or yechimlarni taqdim etish uchun yangi texnologiyalar va yondashuvlarni doimiy o‘rganamiz.",
    "about_page.value_excellence_title": "Mukammallik",
    "about_page.value_excellence_description": "Biz kod sifatidan tortib mijozlar bilan muloqotgacha bo‘lgan har bir jarayonda mukammallikka intilamiz.",
    "about_page.value_collobation_title": "Hamkorlik",
    "about_page.value_collobation_description": "Biz jamoaviy ish va mijozlar bilan sheriklik kuchiga ishonamiz.",
    "about_page.value_integrity_title": "Halollik",
    "about_page.value_integrity_description": "Biz halollik, shaffoflik va axloqiy biznes amaliyotlari asosida ishlaymiz.",
    "portflio_page.description": "Muvaffaqiyatli loyihalarimizni turli sohalar bo‘ylab o‘rganing. Har bir loyiha bizning biznes o‘sishini ta’minlaydigan mukammal yechimlarni yetkazib berishga bo‘lgan sodiqligimizni ifodalaydi.",
    "portflio_page.view_details": "Batafsil ma’lumot",
    "portflio_page.featured_title": "Bizning yirik loyihalarimiz",
    "portflio_page.featured_description": "Eng yirik loyihalarimizni chuqurroq o‘rganing",
    "all.view_all_projects": "Barcha loyihalarni ko‘rish",
  },
  ru: {
    "nav.home": "Главное",
    "nav.about": "О нас",
    "nav.services": "Наши услуги",
    "nav.portfolio": "Портфолио",
    "nav.process": "Процесс работы",
    "nav.contact": "Связаться с нами",
    "hero.title": "Создадим технологии, которые двигают ваш бизнес вперёд!",
    "hero.subtitle": "TrueLiTech - это IT-компания, предоставляющая полный спектр цифровых решений для бизнеса: IT-консалтинг, разработка и сопровождение веб-проектов, мобильных приложений, сайтов и платформ, UI/UX дизайн любой сложности.",
    "hero.cta.start": "Запишитесь на консультацию",
    "hero.cta.work": "Посмотреть наши проекты",
    "services.title": "Наши направления",
    "services.subtitle": "Знаете ли вы, какие возможности откроет цифровизация для вашего бизнеса? Мы поможем вам раскрыть его истинный потенциал. Ниже представлены основные направления, в которых мы работаем.",
    "services.e_commerce_title": "Решения для электронной коммерции",
    "services.e_commerce_description": "Мы разрабатываем веб-сайты и мобильные приложения для онлайн-магазинов, которые помогают привлекать клиентов, управлять сотрудниками и проводить различные виды аналитики.",
    "services.healthcare_title": "Здравоохранение",
    "services.healthcare_description": "Мы разрабатываем веб-сайты и мобильные приложения для клиник и медицинских учреждений, которые помогают привлекать пациентов, управлять персоналом и проводить различные медицинские анализы.",
    "services.finance_and_fintech_title": "Финансы и финтех",
    "services.finance_and_fintech_description": "Избавьтесь от препятствий, мешающих росту вашего финтех-бизнеса! Мы создаем цифровые решения, которые привлекают клиентов, упрощают транзакции и усиливают вашу маркетинговую стратегию.",
    "services.education_title": "Образовательное направление",
    "services.education_description": "Развивайте свой образовательный бизнес! Мы создаем мобильные приложения, CRM и ERP-системы для привлечения студентов, автоматизации обучения и усиления маркетинга.",
    "services.real_estate_title": "Недвижимость",
    "services.real_estate_description": "Упростите сложные процессы в недвижимости! Мы создаем мобильные приложения, CRM и ERP-системы для привлечения клиентов, управления недвижимостью и усиления маркетинга.",
    "services.tourism_title": "Туризм",
    "services.tourism_description": "Знаете ли вы, что путешественники ищут турпакеты в интернете? А у вас нет ни сайта, ни мобильного приложения? Мы создаем цифровые решения для привлечения клиентов, управления бронированиями и усиления маркетинга!",
    "services.start_ups_title": "SaaS и стартапы",
    "services.start_ups_description": "Вашему стартапу нужен быстрый MVP, но не хватает времени и ресурсов? Мы создаем эффективные MVP, чтобы вы могли опередить конкурентов и быстрее завоевать рынок.",
    "services.food_beverage_title": "Общественное Питание",
    "services.food_beverage_description": "Знаете ли вы, что ваши клиенты делают заказы у конкурентов онлайн? А у вас нет ни сайта, ни мобильного приложения? Мы создаем цифровые решения для ресторанов и служб доставки, которые привлекают клиентов, автоматизируют заказы и повышают лояльность!",
    "services.fitness_title": "Фитнес и Велнес",
    "services.fitness_description": "Знаете ли вы, что ваши клиенты ищут фитнес- и оздоровительные услуги онлайн? А у вас нет ни сайта, ни мобильного приложения? Мы создаем цифровые решения для фитнес-клубов и wellness-бизнеса, которые привлекают клиентов, автоматизируют услуги и повышают лояльность!",
    "services.learn_more": "Узнать больше",
    "services.our_process_title": "Наш рабочий процесс",
    "services.our_process_description": "Мы следуем структурированному подходу, чтобы предоставлять высококачественные решения, соответствующие вашим бизнес-требованиям.",
    "services.process_discovery_title": "Открытие",
    "services.process_discovery_description": "Мы начинаем с изучения вашего бизнеса, целей и требований с помощью детальных консультаций.",
    "services.process_research_title": "Исследование и анализ",
    "services.process_research_description": "Наша команда анализирует вашу отрасль, конкурентов и целевую аудиторию, чтобы разработать эффективную стратегию.",
    "services.process_design_title": "Дизайн и планирование",
    "services.process_design_description": "Мы создаем детализированные дизайны и технические спецификации, адаптированные под ваши нужды.",
    "services.process_developement_title": "Разработка",
    "services.process_developement_description": "Наши разработчики создают решение, используя новейшие технологии и лучшие практики.",
    "services.process_testing_title": "Тестирование и контроль качества",
    "services.process_testing_description": "Тщательное тестирование гарантирует, что ваше решение надежно, безопасно и работает оптимально.",
    "services.process_launch_title": "Развертывание и поддержка",
    "services.process_launch_description": "Мы запускаем ваше решение и предоставляем постоянную поддержку и техническое обслуживание для его успешной работы.",
    "portfolio.title": "Наше портфолио",
    "portfolio.description": "Исследуйте наши успешные проекты в различных отраслях и узнайте, как мы помогли бизнесу достичь своих целей.",
    "portfolio.all_projects": "Все проекты",
    "portfolio.e_commerce": "Электронная коммерция",
    "portfolio.healthcare": "Здравоохранение",
    "portfolio.finance": "Финансы",
    "portfolio.education": "Образование",
    "portfolio.real_estate": "Недвижимость",
    "portfolio.startup": "Cтартапы",
    "portfolio.magic": "Magic – передовое решение для аутентификации и управления идентификацией, разработанное для современных веб-приложений.",
    "portfolio.mayo": "Mayo Clinic – cовременное медицинское учреждение, использующее передовые цифровые решения для эффективного управления пациентами и операционной деятельности.",
    "portfolio.luxboutique": "LuxBoutique интернет-магазин – премиальный e-commerce опыт, созданный для люксовых модных брендов, с элегантным дизайном и плавным пользовательским интерфейсом.",
    "portfolio.shopease": "ShopEase интернет платформа - современный, многофункциональный онлайн-маркетплейс с продвинутым управлением товарами, удобной системой оформления заказов и масштабируемой инфраструктурой.",
    "portfolio.skillmaster": "SkillMaster Academy - передовая платформа онлайн-обучения, предлагающая персонализированные курсы, рекомендации на основе ИИ и отслеживание прогресса студентов в реальном времени.",
    "portfolio.globaltechacademy": "Мы разработали мощную ERP-систему, удобное мобильное приложение и динамичный веб-сайт для Global Academy, упростив управление студентами, автоматизировав административные процессы и улучшив доступ к онлайн-обучению. Наши решения повысили операционную эффективность и вовлеченность студентов, сделав образование более удобным и интерактивным.",
    "portfolio.hugson": "Мы разработали современную ERP-систему, удобное мобильное приложение и функциональный веб-сайт для International Hugson University Online. Наши решения цифровизировали образовательный процесс, создав удобный интерфейс для студентов, преподавателей и администрации. Управление курсами, система рейтингов и оценивания были автоматизированы, сделав онлайн-обучение более эффективным и интерактивным.",
    "portfolio.stargate": "Мы разработали передовую ERP-систему, удобное мобильное приложение и профессиональный веб-сайт для Stargate Medical Center. Наши решения оптимизируют управление пациентами, автоматизируют запись на прием и улучшают доступ к медицинским записям. Интуитивно понятная панель управления позволяет врачам эффективно отслеживать лечение, выставлять счета и проводить диагностику, а пациенты могут легко записываться на прием онлайн и пользоваться телемедицинскими услугами. Эта цифровая трансформация повышает операционную эффективность и улучшает качество медицинского обслуживания",
    "portfolio.mondak": "Благодаря мобильным кошелькам, интеграции с банками и QR-платежам, Mondak упрощает финансовые операции. Это безопасный, быстрый и эффективный способ совершения переводов, оплаты счетов и покупок в магазинах без наличных денег для физических лиц и бизнеса.",
    "portfolio.real_property_agency": "Мы создаем современные веб-сайты, мобильные приложения и CRM-системы для агентств недвижимости, девелоперских компаний и частных продавцов. С нашей платформой клиенты могут легко размещать объявления, просматривать недвижимость и заключать сделки. Онлайн-платежи, автоматизированная система бронирования и безопасный обмен данными помогут вашему бизнесу расти!",
    "contact.get_intouch": "Свяжитесь с нами",
    "contact.description": "У вас есть проект? Давайте обсудим, как мы можем помочь вам достичь ваших бизнес-целей.",
    "contact.send_us_message": "Отправьте нам сообщение!",
    "contact.send_description": "Заполните форму ниже, и мы свяжемся с вами как можно скорее!",
    "contact.contact_info": "Контактная информация",
    "contact.contact_info_description": "Свяжитесь с нами напрямую, используя информацию ниже.",
    "contact.telephone": "Телефон",
    "contact.telegram": "Телеграм",
    "contact.address": "Адрес",
    "contact_form.thank_you": "Спасибо за ваше сообщение!",
    "contact_form.success_message": "Ваше сообщение успешно отправлено. Мы свяжемся с вами как можно скорее!",
    "contact_form.name": "Имя",
    "contact_form.enter_name": "Введите имя...",
    "contact_form.phone": "Телефон",
    "contact_form.enter_phone": "Введите телефон...",
    "contact_form.message": "Сообщение",
    "contact_form.tell_us_more": "Расскажите нам о вашем проекте и требованиях...",
    "contact_form.send": "Отправить",
    "contact_form.sending": "Отправляем...",
    "contact_form.name_alert": "Пожалуйста, введите ваше имя!",
    "contact_form.phone_alert": "Пожалуйста, введите ваш номер телефона в формате +998901234567",
    "contact_form.sent": "Отправлено!",
    "contact_form.sent_description": "Мы ответим вам в ближайшее время!",
    "cta.title": "Готовы трансформировать свой бизнес?",
    "cta.description": "Давайте обсудим, как наши индивидуальные IT-решения помогут вам достичь ваших бизнес-целей и роста.",
    "footer.description": "Инновационные IT-решения для бизнеса в разных отраслях. Мы превращаем идеи в мощные цифровые решения.",
    "footer.quick_links": "Быстрые ссылки",
    "footer.all_rights_reserved": "Все права защищены",
    "services_page.title": "Наши услуги",
    "services_page.description": "Комплексные IT-решения, адаптированные под потребности вашей отрасли. Мы объединяем техническую экспертизу с отраслевыми знаниями, чтобы предлагать решения, способствующие росту бизнеса.",
    "services_page.discuss": "Обсудить",
    "services_page.core_service": "Основные сервисы",
    "services_page.core_service_description": "Наш широкий спектр технологических услуг.",
    "services_page.web_development_title": "Веб-разработка",
    "services_page.web_development_description": "Коммерческие и корпоративные веб-сайты, веб-приложения",
    "services_page.web_development_responsive": "Адаптивный дизайн",
    "services_page.web_development_powerful": "Мощные и безопасные платформы электронной коммерции",
    "services_page.web_development_content": "Системы управления контентом (CMS)",
    "services_page.web_development_progressive": "Прогрессивные веб-приложения (PWA)",
    "services_page.web_development_api": "Разработка API",
    "services_page.web_development_custom": "Индивидуальные решения веб-порталов",
    "services_page.mobile_title": "Мобильная разработка",
    "services_page.mobile_description": "Инновационные мобильные приложения для iOS и Android",
    "services_page.mobile_ios": "Разработка приложений для iOS",
    "services_page.mobile_android": "Разработка приложений для Android",
    "services_page.mobile_cross": "Кроссплатформенные решения",
    "services_page.mobile_ui": "UI/UX дизайн мобильных приложений",
    "services_page.mobile_support": "Поддержка и обновление приложений",
    "services_page.mobile_store": "Оптимизация для App Store и Google Play",
    "services_page.ui_title": "UI/UX Дизайн",
    "services_page.ui_description": "Современный дизайн, ориентированный на пользователя",
    "services_page.ui_research": "Исследование пользователей",  
    "services_page.ui_prototyping": "Создание вайрфреймов и прототипов",
    "services_page.ui_visual": "Инновационный визуальный дизайн",
    "services_page.ui_interaction": "Интерактивный дизайн",
    "services_page.ui_testing": "Тестирование удобства использования",
    "services_page.ui_designs": "Дизайн-системы",
    "services_page.mvp_title": "MVP для стартапов",
    "services_page.mvp_description": "Быстрая разработка MVP и запуск на рынок для стартапов",
    "services_page.mvp_reality": "Преобразование бизнес-идей в реальные продукты",
    "services_page.mvp_quick": "Быстрая и минимальная разработка MVP",
    "services_page.mvp_ready": "Решения, готовые для инвесторов",
    "services_page.erp_title": "Разработка ERP/CRM",
    "services_page.erp_description": "Автоматизация бизнес-процессов и повышение эффективности",
    "services_page.erp_finance": "Системы учета и финансового управления",
    "services_page.erp_customer": "Управление взаимоотношениями с клиентами (CRM)",
    "services_page.bots_title": "Телеграм-боты",
    "services_page.bots_description": "Автоматизированные Telegram-боты для бизнеса и услуг",
    "services_page.bots_business": "Разработка Telegram-ботов для бизнеса",
    "services_page.bots_orders": "Онлайн-заказы и автоматизация",
    "services_page.free_consultation": "Свяжитесь с нами сегодня, чтобы обсудить требования вашего проекта и получить бесплатную консультацию.",
    "about_page.title": "О TrueLiTech",
    "about_page.description": "Мы — команда увлеченных технологов, стремящихся помочь бизнесу трансформироваться с помощью инновационных цифровых решений.",
    "about_page.our_story_title": "Наша история",
    "about_page.our_story_description": "От скромного начала до лидерства в отрасли",
    "about_page.founded_with_vision": "Основана с видением",
    "about_page.content": "TrueLiTech была основана в 2019 году с четким видением: помочь бизнесу использовать технологии для достижения своих целей. То, что начиналось как небольшая команда из трех увлеченных разработчиков, выросло в полноценное IT-агентство с более чем 50 экспертами в области разработки, дизайна и стратегии. За эти годы мы помогли сотням клиентов из различных отраслей трансформировать свой бизнес с помощью индивидуальных программных решений, веб-приложений и цифровых стратегий, адаптированных к их конкретным потребностям. Сегодня мы продолжаем внедрять инновации и расширять границы возможного, всегда ставя успех наших клиентов в центр всего, что мы делаем.",
    "about_page.values": "Наши ценности",
    "about_page.values_description": "Принципы, которые определяют нашу работу и отношения.",
    "about_page.value_innovation_title": "Инновации",
    "about_page.value_innovation_description": "Мы постоянно изучаем новые технологии и подходы для предоставления передовых решений.",
    "about_page.value_excellence_title": "Превосходство",
    "about_page.value_excellence_description": "Мы стремимся к совершенству во всем, что делаем — от качества кода до общения с клиентами.",
    "about_page.value_collobation_title": "Сотрудничество",
    "about_page.value_collobation_description": "Мы верим в силу командной работы и партнерства с нашими клиентами.",
    "about_page.value_integrity_title": "Честность",
    "about_page.value_integrity_description": "Мы работаем с честностью, прозрачностью и соблюдением этических бизнес-практик.",
    "portflio_page.description": "Изучите наши успешные проекты в различных отраслях. Каждый проект отражает нашу приверженность предоставлению исключительных решений, способствующих росту бизнеса.",
    "portflio_page.view_details": "Подробнее",
    "portflio_page.featured_title": "Наши крупнейшие проекты",
    "portflio_page.featured_description": "Глубже погрузитесь в наши самые значимые проекты",
    "all.view_all_projects": "Посмотреть все проекты",
  },
  en: {
    "nav.home": "Home Page",
    "nav.about": "About Us",
    "nav.services": "Services",
    "nav.portfolio": "Portfolio",
    "nav.process": "Process",
    "nav.contact": "Contact Us",
    "hero.title": "Turn your ideas into innovation – we create technologies that drive your business forward!",
    "hero.subtitle": "TrueLiTech is an IT company providing a full range of digital solutions for businesses: IT consulting, development and support of web projects, mobile applications, websites, and platforms, as well as complex UI/UX design. We create innovative solutions that help your business grow and evolve within your desired timeframes.",
    "hero.cta.start": "Book a consultation",
    "hero.cta.work": "View our projects",
    "services.title": "Our specialties",
    "services.subtitle": "Do you know what opportunities digitalization can unlock for your business? We help you unleash its true potential. Below are the key industries we specialize in.",
    "services.e_commerce_title": "E-commerce solutions",
    "services.e_commerce_description": "We develop websites and mobile applications for online stores that help attract customers, manage employees, and perform various analytics.",
    "services.healthcare_title": "Healthcare",
    "services.healthcare_description": "We develop websites and mobile applications for clinics and healthcare institutions that help attract patients, manage staff, and perform various medical analytics.",
    "services.finance_and_fintech_title": "Finance and fintech",
    "services.finance_and_fintech_description": "Eliminate the barriers holding back your fintech business! We create digital solutions that attract clients, simplify transactions, and strengthen your marketing strategy.",
    "services.education_title": "Education field",
    "services.education_description": "Grow your education business! We develop mobile apps, CRM, and ERP systems to attract students, automate learning, and boost marketing.",
    "services.real_estate_title": "Real Estate",
    "services.real_estate_description": "Simplify complex real estate processes! We develop mobile apps, CRM, and ERP systems to attract clients, manage properties, and enhance marketing.",
    "services.tourism_title": "Tourism",
    "services.tourism_description": "Did you know that travelers search for tour packages online? But you don’t have a website or mobile app? We create digital solutions to attract clients, manage bookings, and boost your marketing!",
    "services.start_ups_title": "SaaS and Startups",
    "services.start_ups_description": "Does your startup need a fast MVP but lack time and resources? We build efficient MVPs to help you stay competitive and capture the market faster.",
    "services.food_beverage_title": "Food and beverage",
    "services.food_beverage_description": "Did you know that your customers are ordering from competitors online? But you don’t have a website or mobile app? We create digital solutions for restaurants and delivery services to attract clients, automate orders, and boost customer loyalty!",
    "services.fitness_title": "Fitness and Wellness",
    "services.fitness_description": "Did you know that your clients are searching for fitness and wellness services online? But you don’t have a website or mobile app? We create digital solutions for fitness clubs and wellness businesses to attract clients, automate services, and boost customer loyalty!",
    "services.learn_more": "Learn more",
    "services.our_process_title": "Our Work Process",
    "services.our_process_description": "We follow a structured approach to deliver high-quality solutions that meet your business needs.",
    "services.process_discovery_title": "Discovery",
    "services.process_discovery_description": "We start by understanding your business, goals, and requirements through in-depth consultations.",
    "services.process_research_title": "Research and analysis",
    "services.process_research_description": "Our team researches your industry, competitors, and target audience to inform our strategy.",
    "services.process_design_title": "Design and planning",
    "services.process_design_description": "We create detailed designs and technical specifications tailored to your specific needs.",
    "services.process_developement_title": "Development",
    "services.process_developement_description": "Our developers build your solution using the latest technologies and best practices.",
    "services.process_testing_title": "Testing and QA",
    "services.process_testing_description": "Rigorous testing ensures your solution is robust, secure, and performs optimally.",
    "services.process_launch_title": "Deployment and support",
    "services.process_launch_description": "We launch your solution and provide ongoing support and maintenance to ensure success.",
    "portfolio.title": "Our Portfolio",
    "portfolio.description": "Explore our successful projects across various industries and see how we've helped businesses achieve their goals.",
    "portfolio.all_projects": "All projects",
    "portfolio.e_commerce": "E-commerce",
    "portfolio.healthcare": "Healthcare",
    "portfolio.finance": "Finance",
    "portfolio.education": "Education",
    "portfolio.real_estate": "Real Estate",
    "portfolio.startup": "Start Ups",
    "portfolio.magic": "Magic – a cutting-edge authentication and identity management solution designed for modern web applications.",
    "portfolio.mayo": "Mayo Clinic – a modern healthcare facility leveraging advanced digital solutions for seamless patient management and operational efficiency.",
    "portfolio.luxboutique": "LuxBoutique online store – a premium e-commerce experience tailored for luxury fashion brands, offering elegant design and smooth user experience.",
    "portfolio.shopease": "ShopEase e-commerce platform - a modern, feature-rich online marketplace with advanced product management, seamless checkout, and a scalable infrastructure.",
    "portfolio.skillmaster": "SkillMaster Academy - a cutting-edge e-learning platform offering personalized courses, AI-driven recommendations, and real-time progress tracking for students.",
    "portfolio.globaltechacademy": "We developed a powerful ERP system, a user-friendly mobile app, and a dynamic website for Global Academy, streamlining student management, automating administrative tasks, and enhancing online learning accessibility. Our solutions have improved operational efficiency and student engagement, making education more seamless and interactive.",
    "portfolio.hugson": "We developed a modern ERP system, a user-friendly mobile app, and a functional website for International Hugson University Online. Our solutions digitized the educational process, creating a seamless interface for students, faculty, and administration. Course management, grading, and assessment systems were automated, making online learning more efficient and interactive.",
    "portfolio.stargate": "We have built an advanced ERP system, a user-friendly mobile application, and a professional website for Stargate Medical Center. Our solutions streamline patient management, automate appointment scheduling, and enhance medical record accessibility. With an intuitive dashboard, doctors can efficiently track treatments, billing, and diagnostics, while patients enjoy seamless online booking and telemedicine support. This digital transformation boosts operational efficiency and ensures top-tier healthcare service delivery",
    "portfolio.mondak": "With Mobile Wallets, Bank Integrations, and QR Payments, Mondak simplifies payment processes. It is secure, fast, and efficient, enabling individuals and businesses to make money transfers, bill payments, and in-store purchases without cash.",
    "portfolio.real_property_agency": "We develop modern websites, mobile applications, and CRM systems for real estate agencies, developers, and independent sellers. With our platform, clients can easily list properties, browse available real estate, and close deals efficiently. Online payments, automated booking systems, and secure data exchange will elevate your business to new heights!",
    "contact.get_intouch": "Get in touch",
    "contact.description": "Let's discuss how we can help you achieve your business goals.",
    "contact.send_us_message": "Send us a message!",
    "contact.send_description": "Fill out the form below and we'll get back to you as soon as possible!",
    "contact.contact_info": "Contact information",
    "contact.contact_info_description": "Reach out to us directly using the information below.",
    "contact.telephone": "Telephone",
    "contact.telegram": "Telegram",
    "contact.address": "Address",
    "contact_form.thank_you": "Thank you!",
    "contact_form.success_message": "Your message has been sent successfully. We'll get back to you as soon as possible!",
    "contact_form.name": "Name",
    "contact_form.enter_name": "Enter your name...",
    "contact_form.phone": "Phone",
    "contact_form.enter_phone": "Enter your phone number...",
    "contact_form.message": "Message",
    "contact_form.tell_us_more": "Tell us about your project and requirements...",
    "contact_form.send": "Send",
    "contact_form.sending": "Sending...",
    "contact_form.name_alert": "Please enter your name!",
    "contact_form.phone_alert": "Please enter your phone number!",
    "contact_form.sent": "Message sent!",
    "contact_form.sent_description": "We will get back to you as soon as possible!",
    "cta.title": "Ready to Transform Your Business?",
    "cta.description": "Let's discuss how our tailored IT solutions can help you achieve your business goals and drive growth.",
    "footer.description": "Innovative IT solutions for businesses across various industries. We transform ideas into powerful digital experiences.",
    "footer.quick_links": "Quick Links",
    "footer.all_rights_reserved": "All rights reserved",
    "services_page.title": "Our services",
    "services_page.description": "Comprehensive IT solutions tailored to your industry needs. We combine technical expertise with industry knowledge to deliver solutions that drive business growth.",
    "services_page.discuss": "Discuss your project",
    "services_page.core_service": "Core services",
    "services_page.core_service_description": "Our comprehensive range of technology services.",
    "services_page.web_development_title": "Web Development",
    "services_page.web_development_description": "Commercial and corporate websites, web applications",
    "services_page.web_development_responsive": "Responsive design",
    "services_page.web_development_powerful": "Powerful and secure e-commerce platforms",
    "services_page.web_development_content": "Content management systems (CMS)",
    "services_page.web_development_progressive": "Progressive web apps (PWA)",
    "services_page.web_development_api": "API development",
    "services_page.web_development_custom": "Custom web portal solutions",
    "services_page.mobile_title": "Mobile Development",
    "services_page.mobile_description": "Innovative mobile applications for iOS and Android",
    "services_page.mobile_ios": "iOS app development",
    "services_page.mobile_android": "Android app development",
    "services_page.mobile_cross": "Cross-platform solutions",
    "services_page.mobile_ui": "Mobile UI/UX design",
    "services_page.mobile_support": "App maintenance and support",
    "services_page.mobile_store": "App Store and Google Play optimization",
    "services_page.ui_title": "UI/UX Design",
    "services_page.ui_description": "Modern design tailored to user needs",
    "services_page.ui_research": "User research",
    "services_page.ui_prototyping": "Wireframing and prototyping",
    "services_page.ui_visual": "Innovative visual design",
    "services_page.ui_interaction": "Interaction design",
    "services_page.ui_testing": "Usability testing",
    "services_page.ui_designs": "Design systems",
    "services_page.mvp_title": "MVP for Startups",
    "services_page.mvp_description": "Rapid MVP development and market launch for startups",
    "services_page.mvp_reality": "Transforming business ideas into real products",
    "services_page.mvp_quick": "Quick and minimal MVP development",
    "services_page.mvp_ready": "Investor-ready solutions", 
    "services_page.erp_title": "ERP/CRM Development",
    "services_page.erp_description": "Automating business processes and improving efficiency",
    "services_page.erp_finance": "Accounting and financial management systems",
    "services_page.erp_customer": "Customer relationship management (CRM)",
    "services_page.bots_title": "Telegram Bots",
    "services_page.bots_description": "Automated Telegram bots for business and services",
    "services_page.bots_business": "Telegram bot development for business",
    "services_page.bots_orders": "Online orders and automation",
    "services_page.free_consultation": "Contact us today to discuss your project requirements and get a free consultation.",
    "about_page.title": "About TrueLiTech",
    "about_page.description": "We're a team of passionate technologists dedicated to helping businesses transform through innovative digital solutions.",
    "about_page.our_story_title": "Our story",
    "about_page.our_story_description": "From humble beginnings to industry leadership",
    "about_page.founded_with_vision": "Founded with a Vision",
    "about_page.content": "TrueLiTech was founded in 2019 with a clear vision: to help businesses leverage technology to achieve their goals. What started as a small team of three passionate developers has grown into a full-service IT agency with over 50 experts across development, design, and strategy. Over the years, we've helped hundreds of clients across various industries transform their businesses through custom software solutions, web applications, and digital strategies tailored to their specific needs. Today, we continue to innovate and push the boundaries of what's possible, always keeping our clients' success at the heart of everything we do.",
    "about_page.values": "Our values",
    "about_page.values_description": "The principles that guide our work and relationships.",
    "about_page.value_innovation_title": "Innovation",
    "about_page.value_innovation_description": "We constantly explore new technologies and approaches to deliver cutting-edge solutions.",
    "about_page.value_excellence_title": "Excellence",
    "about_page.value_excellence_description": "We strive for excellence in everything we do, from code quality to client communication.",
    "about_page.value_collobation_title": "Collaboration",
    "about_page.value_collobation_description": "We believe in the power of teamwork and partnership with our clients.",
    "about_page.value_integrity_title": "Integrity",
    "about_page.value_integrity_description": "We operate with honesty, transparency, and ethical business practices.",
    "portflio_page.description": "Explore our successful projects across various industries. Each project represents our commitment to innovation delivering exceptional solutions that drive business growth.",
    "portflio_page.view_details": "View details",
    "portflio_page.featured_title": "Featured Case Studies",
    "portflio_page.featured_description": "Dive deeper into our most impactful projects",
    "all.view_all_projects": "View all projects",
  },
}

const LanguageContext = createContext<LanguageContextType>({
  currentLanguage: "ru",
  setLanguage: () => {},
  languages,
  t: (key) => key,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState("ru")

  useEffect(() => {
    // Get browser language or saved preference
    const savedLanguage = localStorage.getItem("language") || navigator.language.split("-")[0]
    if (languages.some((lang) => lang.code === savedLanguage)) {
      setCurrentLanguage(savedLanguage)
    }
  }, [])

  const setLanguage = (code: string) => {
    setCurrentLanguage(code)
    localStorage.setItem("language", code)
  }

  const t = (key: string) => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, languages, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)

